#!/usr/bin/env ruby

# 直接 $ ruby bin/jm.rb で実行したときに必要
lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "jm_thor"
require "thor"

module JmThor
  class CLI < Thor
    class_option :help, type: :boolean, aliases: '-h', desc: "Show help message."
    class_option :version, type: :boolean, desc: "Show version."
    default_command :jm

    desc "jm", "Register ticket name and time."
    method_option :ticket, type: :string, aliases: ["-t", "--ticket"]
    method_option :manpower, type: :string, aliases: ["-m", "--manpower"]
    method_option :comment, type: :string, aliases: ["-c", "--comment"]
    def jm(*args)
      JiraManpower::Register.new.register(
        options[:ticket],
        options[:manpower],
        options[:comment]
      )
    end

    desc "jmlog", "Show manpower logs."
    method_option :date, type: :string # YYYY-MM-DDの形式で指定。
    method_option :all
    method_option :name, type: :string
    def jmlog(*args)
      if options[:date]
        JiraManpower::Logger.new.show_datelog(options[:date])
      elsif options[:all]
        JiraManpower::Logger.new.show_log_all
      elsif options[:name]
        JiraManpower::Logger.new.show_log(options[:name])
      else
        # 引数なしの場合は当日のログを閲覧する
        JiraManpower::Logger.new.show_datelog(Date.today.to_s)
      end
    end
  end
end

JmThor::CLI.start
